"""add ontology object_type link_type object_instance link_instance

Revision ID: 63e7b4c0b009
Revises: b2322304a207
Create Date: 2026-03-17 21:05:39.809785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63e7b4c0b009'
down_revision: Union[str, Sequence[str], None] = 'b2322304a207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_types',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('link_types',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_object_type_id', sa.String(length=64), nullable=False),
    sa.Column('target_object_type_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_object_type_id'], ['object_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_object_type_id'], ['object_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_types_source_object_type_id'), 'link_types', ['source_object_type_id'], unique=False)
    op.create_index(op.f('ix_link_types_target_object_type_id'), 'link_types', ['target_object_type_id'], unique=False)
    op.create_table('object_instances',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('object_type_id', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_instances_object_type_id'), 'object_instances', ['object_type_id'], unique=False)
    op.create_table('link_instances',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('link_type_id', sa.String(length=64), nullable=False),
    sa.Column('source_object_id', sa.String(length=64), nullable=False),
    sa.Column('target_object_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['link_type_id'], ['link_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_object_id'], ['object_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_object_id'], ['object_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_instances_link_type_id'), 'link_instances', ['link_type_id'], unique=False)
    op.create_index(op.f('ix_link_instances_source_object_id'), 'link_instances', ['source_object_id'], unique=False)
    op.create_index(op.f('ix_link_instances_target_object_id'), 'link_instances', ['target_object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_instances_target_object_id'), table_name='link_instances')
    op.drop_index(op.f('ix_link_instances_source_object_id'), table_name='link_instances')
    op.drop_index(op.f('ix_link_instances_link_type_id'), table_name='link_instances')
    op.drop_table('link_instances')
    op.drop_index(op.f('ix_object_instances_object_type_id'), table_name='object_instances')
    op.drop_table('object_instances')
    op.drop_index(op.f('ix_link_types_target_object_type_id'), table_name='link_types')
    op.drop_index(op.f('ix_link_types_source_object_type_id'), table_name='link_types')
    op.drop_table('link_types')
    op.drop_table('object_types')
    # ### end Alembic commands ###
