"""add_source_target_key_property_to_link_type

Revision ID: db14c6e59816
Revises: 0693b2dd26cf
Create Date: 2026-03-19 11:38:31.120339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db14c6e59816'
down_revision: Union[str, Sequence[str], None] = '0693b2dd26cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_types', sa.Column('source_key_property', sa.String(length=128), nullable=True))
    op.add_column('link_types', sa.Column('target_key_property', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_types', 'target_key_property')
    op.drop_column('link_types', 'source_key_property')
    # ### end Alembic commands ###
